apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ai-gateway
  labels:
    app: code-review-api
    component: api
  annotations:
    # NLB en lugar de CLB: más barato y mejor rendimiento para tráfico TCP/HTTP
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: code-review-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
